### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by mike632t** [macmpi/x11-calc-flatpak#1]
Tried building using the following commands
```
$ flatpak-builder -v --disable-rofiles-fuse --force-clean build-dir com.github.mike632t.x11-calc.yaml
```
```
$ flatpak-builder --user --install --disable-rofiles-fuse --force-clean build-dir com.github.mike632t.x11-calc.yaml
```
When I included the ```--disable-rofiles-fuse``` option these commands seemed to work (there are some warnings) but I can't build the bundle.
```
$ flatpak build-bundle ~/.local/share/flatpak/repo x11-calc.flatpak com.github.mike632t.x11-calc master
error: Refspec 'app/com.github.mike632t.x11-calc/x86_64/master' not found
```

**Comment by macmpi** [comment]
hum... strange.
Did the installed app work as expected?
Have you tried installing the pre-built bundle linked from README?

**Comment by mike632t** [comment]
Interestingly I get a similar problem with the pre-built bundle.  Unfortunately I know next to nothing about Flatpak (though I can now spell it correctly!) so I'm not sure how to do about debugging this. 
```
$ cd ~
$ wget https://github.com/macmpi/x11-calc-flatpak/releases/download/v0.1/x11-calc.flatpak

  :
  :
  :

$ flatpak run com.github.mike632t.x11-calc

Note that the directories 

'/var/lib/flatpak/exports/share'
'/home/user/.local/share/flatpak/exports/share'

are not in the search path set by the XDG_DATA_DIRS environment variable, so
applications installed by Flatpak may not appear on your desktop until the
session is restarted.

error: app/com.github.mike632t.x11-calc/x86_64/master not installed
$ 
```

Added some diagnostic output which may help.

```
$ flatpak list
Name                         Application ID                              Version          Branch              Installation
Freedesktop Platform         org.freedesktop.Platform                    23.08.10         23.08               user
Mesa                         org.freedesktop.Platform.GL.default         23.3.2           23.08               user
Mesa (Extra)                 org.freedesktop.Platform.GL.default         23.3.2           23.08-extra         user
openh264                     org.freedesktop.Platform.openh264           2.1.0            2.2.0               user
Freedesktop SDK              org.freedesktop.Sdk                         23.08.10         23.08               user
$ flatpak remotes -v
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/user/.local/share/flatpak
flathub	user
$ 
```

**Comment by macmpi** [comment]
I'm not an expert either...
Maybe Flatpak is not installed properly in your distro? (re `XDG_DATA_DIRS` complaints).
You may need to install `org.freedesktop.Platform` and `org.freedesktop.Sdk`
`flatpak list` would display what's installed.

BTW, it would help `x11-calc` does not use hard-coded $HOME (i.e. for `.dat` files), but rather abides to [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by macmpi** [comment]
Can you try installing some other "reference"  apps via [flathub](https://flathub.org/) for instance: this may validate your setup is fine?
(in general system needs to be restarted after initial flatpak setup: there are distro-specific install guides on flathub)

**Comment by mike632t** [comment]
Well I just followed the instructions of the flatpak site to install flatpak which for Debian is just... 
```
# apt-get install flatpak
```
However, I ignored the instructions to install the Flatpak plugin for GNOME Software and Plasma Discover Flatpak backend as I'm not using either GNOME or KDE and skipped the instruction to add the flatpak repository, as I wasn't planning on installing anything from the repo.   

Rebooted - but had to power off as the reboot hung.

Added GNOME plugin in case something was missing.

```
# apt-get install gnome-software-plugin-flatpak
```
Rebooted again - but it made no difference.

I did think about trying to install another package from flathub but decided not to when the command to configure the repository prompted me for my root password which was a bit unexpected..

**Comment by macmpi** [comment]
will try to spin a Debian VM with flatpak environment when I can.

**Comment by mike632t** [comment]
> BTW, it would help `x11-calc` does not use hard-coded $HOME (i.e. for `.dat` files), but rather abides to [XDG spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

It is a question of targeting the lowest common denominator, not everything follows freedesktop standards, and even if you do try to follow the standard the $XDG_DATA_HOME path is still defined relative to $HOME and it gets quite complicated quickly because sub folders are involved, so you then have to worry about creating them if they don't exist (in a cross platform way), and setting or inheriting the correct properties.

I agree that using $HOME probably is not be the best solution or the most elegant, but it is does seem to be the simplest, as it is nearly always defined, it should exist, and will probably be writable.  I also wanted to avoid introducing any dependencies on libraries that might not be available on other systems.

**Comment by mike632t** [comment]
> will try to spin a Debian VM with flatpak environment when I can.

Thanks that should be interesting - I've probably done something silly or quite possibly don't have a required package installed, which would be a bug in flatpak, but it would not be the first time that I've come across a package that depends on another package that is only suggested or recommended rather then actually being a dependency.    

My test machine is running Debian 11 at the moment, but I can install Debian 12 easily enough.

**Comment by macmpi** [comment]
> I agree that using $HOME probably is not be the best solution or the most elegant,

It seems `x11-calc` main use is for .dat file: maybe using XDG_DATA_HOME (if set) and reverting to $HOME (if not) would make desktops integration leaner.

**Comment by macmpi** [comment]
> > will try to spin a Debian VM with flatpak environment when I can.
> 
> Thanks that should be interesting

Did setup a brand new bookworm VirtualBox VM with `xfce4` & `xfce4-goodies`, installed `flatpak`, added flathub repo as per [this](https://flathub.org/setup/Debian), and installed `x11-calc.flatpak` with no major issues: app worked as expected.
![VBoxDebianTest](https://github.com/macmpi/x11-calc-flatpak/assets/16296055/76dfa0b3-6ef9-4f85-bd4c-1e78962df543)

**Comment by mike632t** [comment]
> > I agree that using $HOME probably is not be the best solution or the most elegant,
> 
> It seems `x11-calc` main use is for .dat file: maybe using XDG_DATA_HOME (if set) and reverting to $HOME (if not) would make desktops integration leaner.

I like that idea - do you want to open an issue against the x11-calc repo ?

If I get a chance I'll have a go at implementing it this weekend...

**Comment by mike632t** [comment]
I'll have another go on a separate VM later this week end.

Not sure if you have noticed but I suspect you are using Wayland as the option to maximise the window is present in your screenshot.  Unfortunately, I don't think there is anything I can do about that as `xwayland` seems to ignore window manager hints.

**Comment by macmpi** [comment]
I did not enable Wayland in flatpak build (i.e. yaml): only x11.
Will update files in the repo when stable is released.

**Comment by mike632t** [comment]
Probably doesn't matter what Flatpak is built with, as even if the package/program only use X11 the window manager on the host can still be using Wayland, in which case the X11 calls are handled by `xwayland` (which is where the bug is)

**Comment by macmpi** [comment]
pushed current changes.
You may want to try to install [x11-calc.flatpak](https://github.com/macmpi/x11-calc-flatpak/files/14316757/x11-calc.flatpak.tar.gz) built from unstable (`flatpak install x11-calc.flatpak`)

**Comment by macmpi** [comment]
I guess we can close this one?

**Comment by mike632t** [comment]
I'll have another go at building the package and see what happens...

**Comment by mike632t** [comment]
After installing `elfutils` and `fuse` I needed to download the runtime SDK

```
$ flatpak install flathub org.freedesktop.Sdk/x86_64/23.08
```
However I now get an interesting icon related error, I assume this still works for you so I'm guessing it is another missing package...?
```
Please review the exported files and the metadata
Committing stage finish to cache
Exporting io.github.mike632t.x11_calc to repo
error: /home/system/x11-calc-flatpak-main/build-dir/export/share/icons/hicolor/scalable/apps/io.github.mike632t.x11_calc.svg is not a valid icon: Format not recognized
```

**Comment by mike632t** [comment]
Fixed it I was missing `librsvg2-common` ...
