### ISSUE TITLE
Submitting to flathub

### ISSUE THREAD

**Issue by macmpi** [macmpi/x11-calc-flatpak#2]
@mike632t, I am getting close to initiate [submission](https://docs.flathub.org/docs/for-app-authors/submission/) to flathub, and wanted to check a few things with you first.
- do you wish to handle that part on your side, or is it ok for me to do (I'm fine both ways)?
- you may want to review/comment [metainfo](https://github.com/macmpi/x11-calc-flatpak/blob/main/x11-calc.metainfo.xml) file, so that you are fine with it. More info [here](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines): it's used by [flathub](https://flathub.org/) to present software on store.
Some apps maintain it in their main tree, though some element might look specific to flathub/flatpak: let me know if I shall send a PR to your repo.
note: app ID construction follows recommended guidelines from [AppStream MetaInfo Creator](https://www.freedesktop.org/software/appstream/metainfocreator/#/)
- it would be practical to line-up on release-versioning scheme, so that things are smooth for users, updates, etc.
Do you intend to tag releases with some versioning info? Shall we allow for an extra minor digit for eventual packaging-related fixes?

Thanks for your thoughts.

**Comment by mike632t** [comment]
I don't mind if you to do it - after all you created the package!  (Do you want to fork the source to the version you package?) 

Note - There will be another update shortly as I just found another two bugs while testing on tru64... One with the code that searches for the application data directory and the other could be a nice to have if I can make it work!

I'll take a look at the metainfo file and comment back here when I've sorted out the bug above.

Currently I'm still at notionally at version 0.10 and although I do define a build number in each source file it applies only to that file.  Sorting this out and moving all the version history to a single file is something I'm thinking about but would be a lot of work. 

If you download the source code from github using wget (zip file) the commit ID in the source should automatically be populated (I don't know what happens if you do a `git clone`) and the commit ID is included the version text. This has the advantage that it is unique but doesn't (easily) let you see which of two versions is newer.
````
x11-calc-25c: Version 0.10 [Commit ID: 4e0a6a6] 16 Feb 24 22:56:05 (Build: 0118)
````

**Comment by macmpi** [comment]
Here is what I get with cloning (automated process in build):
`x11-calc-34c: Version 0.10 [Commit ID: $Format:%h$] 17 Feb 24 18:12:12 (Build: 0118)`

Anyhow flathub [requires versioning ](https://docs.flathub.org/docs/for-app-authors/metainfo-guidelines/#release)to figure-out which is latest and seamlessly update apps, so commit# is not enough.
_Applications must supply a releases tag in their MetaInfo to pass validation_

I do not intend to fork, and I think flathub would not like that either: we need to refer to the upstream project.
So better to find common grounds for versioning I think.

**Comment by mike632t** [comment]
Can you build you binaries using `wget` instead of `git clone`?  That would fix the strange `[Commit ID: $Format:%h$]` field and having the commit ID can make debugging easier.   I don't want to drop it as it is about the only way to identify what people are using when they build the application from source.

Historically I have kept a separate change history and version/build number in each of my source files which really doesn't translate easily to a single version number for the whole project.   I've tidied up the sources to remove the version numbers from everything apart from x11-calc and incremented that to 0.11 (major version 0 minor version 11).  However, merging all the change histories together to come up with an over all build number isn't something I want to even think about, so for now the build number will just reflect the number of changes to x11-calc.

If I remember to increment the version in x11-calc each time I merge any changes into stable which by design should not be that often, would that give you the sort of version numbering scheme you need ? 

Is the intention to update the flatpak packages automatically?  (I suspect that would require a separate file to track the version number).

I'm also thinking about incorporating the build number into the version number, which would look make the version number look like this:
````
x11-calc-21: Version 0.11.0119 [Commit ID: 67a7f77] 17 Feb 24 21:18:45
````
Instead of:
````
x11-calc-21: Version 0.11 [Commit ID: 67a7f77] 17 Feb 24 21:18:45 (Build: 0119)
`````

**Comment by macmpi** [comment]
> Can you build you binaries using `wget` instead of `git clone`?

Yes, can do.
Need to compute sha sum in that case as .yaml build file requires it then.
Verified commit ID is indeed reported.
Unsure why commit ID can not be  obtained on git.

>If I remember to increment the minor (or even major) version in x11-calc each time I merge any changes into stable which by design should not be that often, would that give you the sort of version numbering scheme you need ?

I think so.
In fact it's not required to create a Github tag at each individual commit: you may set a tag when you feel it's meaningful enough to cast a release.
According to this [guideline](https://www.freedesktop.org/software/appstream/docs/chap-AppStream-Misc.html#spec-vercmp-recommendations), and related [Semantic Versioning](https://semver.org/), it should follow the MAJOR.MINOR.PATCH model.
~~I'm not sure what happens if packaging itself need a version bump for a given upstream release (fix for packaging issue)...~~

>Is the intention to update the flatpak packages automatically? (I suspect that would require a separate file to track the version number).

Yes: metainfo file does list such versions list. `flatpak update` command uses that file to trigger updates.

**Comment by mike632t** [comment]
Do you want me to implement the version number as below - being a backward compatible bug fix to the version number it shouldn't mean a change to the version number... 
````
x11-calc-21: Version 0.11.0119 [Commit ID: 67a7f77] 17 Feb 24 21:18:45
````

**Comment by mike632t** [comment]
When you are ready if you want to add the metainfo file into the x11-calc directory itself and create a pull request I'll merge it in

**Comment by mike632t** [comment]
Think I have got flatpak working on a test machine, the missing 'magic sauce' was `fuse`.

It works but I can't believe the size of the downloads required to get a simple console application to run, in addition to flatpak and its dependencies installing the application needed to download approximately 660MB! 

I suspect that this is down the to runtime selected in the package so I'm hoping x11-calc has less of a footprint... 

```
        ID                                             Branch            Op           Remote            Download
 1. [✓] org.freedesktop.Platform.GL.default            21.08             i            flathub           130.6 MB / 129.8 MB
 2. [✓] org.freedesktop.Platform.Locale                21.08             i            flathub            18.0 kB / 326.8 MB
 3. [✓] org.freedesktop.Platform.openh264              2.0               i            flathub             1.8 MB / 1.5 MB
 4. [✓] org.freedesktop.Platform                       21.08             i            flathub           199.6 MB / 202.1 MB
 5. [✓] fr.rubet.rpn                                   stable            i            flathub             1.1 MB / 617.3 kB
```
```
$ flatpak run fr.rubet.rpn
rpn v2.5
Type h or help for more information.
rpn> 48 47.8 -
0.20000000000000000000000000000000000004
rpn> .2 -
3.746888243246041431650347712395908098e-38
rpn>
```
All those MB and no decimal number library... 

Looking forward to testing it.

**Comment by macmpi** [comment]
>I suspect that this is down the to runtime selected in the package so I'm hoping x11-calc has less of a footprint...

First install may be big download due to environment. Updates are just deltas

>Looking forward to testing it.

You may try [this one]() for now:
`flatpak install x11-calc.flatpak`

**Comment by macmpi** [comment]
> Do you want me to implement the version number as below - being a backward compatible bug fix to the version number it shouldn't mean a change to the version number...
> 
> ```
> x11-calc-21: Version 0.11.0119 [Commit ID: 67a7f77] 17 Feb 24 21:18:45
> ```

As you prefer: guess might be quite practical for you to better track-down versions for bug reports.

>add the metainfo file into the x11-calc directory itself and create a pull request

Ok, will do.
Then it will be easier for you to sync-up release info by updating that file too in the process (metainfo can list up to 15 releases info max I think).

**Comment by macmpi** [comment]
> Unsure why commit ID can not be obtained on git.

Trying to find how `Format` keyword can be expanded after a `git fetch`, like with [`git archive`](https://git-memo.readthedocs.io/en/latest/git_archive.html#git-keyword-expansion).
Unsure sth may be set in project `.gitconfig` or else...
`git show --format=%h` after `git fetch` and before `make` does not help either.

**Comment by mike632t** [comment]
> You may try[ this one](https://github.com/macmpi/x11-calc-flatpak/files/14322030/x11-calc.flatpak.tar.gz) for now: `flatpak install x11-calc.flatpak`

Worked a treat (might be better to make make the hp33c or hp25c the default, there is only so much you can do  with the hp35!) 

```
$ flatpak install --user  x11-calc.flatpak
Required runtime for io.github.mike632t.x11_calc/x86_64/master (runtime/org.freedesktop.Platform/x86_64/23.08) found in remote flathub
        ID                                           Branch               Op         Remote                   Download
 1. [✓] org.freedesktop.Platform.GL.default          23.08                i          flathub                  163.0 MB / 162.3 MB
 2. [✓] org.freedesktop.Platform.GL.default          23.08-extra          i          flathub                   17.9 MB / 162.3 MB
 3. [✓] org.freedesktop.Platform.Locale              23.08                i          flathub                   17.9 kB / 359.9 MB
 4. [✓] org.freedesktop.Platform.openh264            2.2.0                i          flathub                  883.7 kB / 944.3 kB
 5. [✓] org.freedesktop.Platform                     23.08                i          flathub                  218.7 MB / 225.6 MB
 6. [✓] io.github.mike632t.x11_calc                  master               i          x11_calc1-origin         0 bytes

Installation complete.
$ 
$ flatpak run io.github.mike632t.x11_calc
x11-calc-35: Version 0.11 [Commit ID: 67a7f77] 17 Feb 24 22:31:51 (Build: 0119)
ROM Size :  768 words 
$ 
```
Approximately 400Mb runtime but it does work.

**Comment by macmpi** [comment]
> Worked a treat

Nice. Thanks for the PRs.

Launcher is a bit awkward as shell only...hope it won't repel users too much.
Anyhow I don't think it'll be used a lot once set anyway: people tend to stick to their preferred model.
Let me know if you are in for a GUI model/setup picker at some point.

Have you settled on the versioning scheme?

**Comment by macmpi** [comment]
> > Unsure why commit ID can not be obtained on git.
> 
> Trying to find how `Format` keyword can be expanded after a `git fetch`, like with [`git archive`](https://git-memo.readthedocs.io/en/latest/git_archive.html#git-keyword-expansion). Unsure sth may be set in project `.gitconfig` or else... `git show --format=%h` after `git fetch` and before `make` does not help either.

Reading [this](https://stackoverflow.com/questions/16524225/how-can-i-populate-the-git-commit-id-into-a-file-when-i-commit), it seems like `git log -1 HEAD --format=%h` would report what you need for inclusion in code: anything you could use in a build time variable for instance?
Being able to build from git fetch would be nice, not just from a flatpak perspective.
Thoughts?

**Comment by mike632t** [comment]
Ok it is more than a bit of a fudge but I think I've come up with a solution - I've just pushed my changes to the `unstable` branch but I need to test to see what happens if I download the code using `wget` and then build it.

See what you think... 

It would be nice if it didn't set `COMMIT` if there were outstanding changes that have not been committed.

**Comment by mike632t** [comment]
Updated version number format as well

**Comment by mike632t** [comment]
Results of my testing earlier with flatpak - I was slightly surprised that Flatpak didn't object but everything just worked.

![Screenshot_debian12_2024-02-18_20:23:24](https://github.com/macmpi/x11-calc-flatpak/assets/1799044/4ea49689-ee0b-48c0-975d-7c35dc178439)

**Comment by macmpi** [comment]
Looks good: rebuilt with git fetch from unstable:
`x11-calc-25c: Version 0.11.0120 [Commit Id : c06f6b1] 18 Feb 24 22:59:08`

**Comment by mike632t** [comment]
I still need to do some more testing, but if there are no issues I'll merge the changes into stable (probably tomorrow evening).

**Comment by mike632t** [comment]
Pushed changes to `stable`...

I'm sure one of my commit comments got put against the wrong change but it is all there are ready to go - I hope!!

**Comment by mike632t** [comment]
NOT GOOD, one of my bug fixes seem to have regressed !!! Will fix tomorrow evening

**Comment by macmpi** [comment]
Could build successfully with clone.
One detail thought: build date does not seem to fully manage timezone: built plain `x11-calc `and `x11-calc-flatpak` in a row. Former reports build date in my local timezone, latter seemingly reports in UTC - none mentioned timezone it referred to.
Build date may need to report which timezone date refers to, or always reports in UTC.

> add the metainfo file into the x11-calc directory itself and create a pull request

done.
In fact I'm pondering on what's the best location for `metainfo.xml` file maintenance, and release updates changes...
2 files (minimum) will need to be updated at each release with tags&commit refs:
- `io.github.mike632t.x11_calc.yaml` (must be on flathub repo, governs automated build and publish)
- `x11-calc.metainfo.xml` (flathub repo or x11-calc repo).

Unsure what is best/simpler to manage: keep the 2 in same location (flathub), or one on each side?
Looking at existing flathub apps, we can find apps either way.

What's your preference? In any case, you will be given write access to flathub infra for [maintenance](https://docs.flathub.org/docs/for-app-authors/maintenance/), even if I create it initially.

**Comment by mike632t** [comment]
During my testing I was getting some random behaviour when loading and saving state to a data file.

There were a couple of occasions where I saw the state loaded successfully from a data file in `.local/share/x11-calc/` but when the program existed it appeared unable to save the state in the same place and so defaulted to `$HOME`
```
$ bin/x11-calc-25c
x11-calc-25c: Version 0.11.0120 [Commit Id : 9b362bb] 19 Feb 24 10:39:15
ROM Size : 2048 words
Loading '/home/user/.local/share/x11-calc/x11-calc-25c.dat'.
Saving '/home/user/.x11-calc-25c.dat'.
Saving '/home/use/.x11-calc-25c.dat'.
```

And even more inexplicably I got the following error on one occasion, in the short interval between clicking on the off button and then the program existing (when it saves the state again), it appeared to be unable to access `.local/share/x11-calc` one the second attempt.
```
$ bin/x11-calc-25c prg/x11-calc-25c-factorial.dat
x11-calc-25c: Version 0.11.0120 [Commit Id : 9b362bb] 19 Feb 24 10:39:15
ROM Size : 2048 words
Loading 'prg/x11-calc-25c-factorial.dat'.
Saving '/home/user/.local/share/x11-calc/x11-calc-25c.dat'.
Saving '/home/user/.x11-calc-25c.dat'.
```
I've added some code (in gcc-exists.c) to explicitly check to see if `stat()` succeeds when checking if a path is a file or a directory (which should not have been necessary as the calling code checks the path exists first), and I now also zero the contents of the file data structure to avoid 'accidental' reuse.  I can't be sure this has fixed the problem as the original error only occurred three or four times during a whole evening of testing (related to the commit IDs), so it wasn't easily reproducible but so far this evening I've not seen it happen again.  

It won't affect the Flatpak version anyway as if `XDG_DATA_HOME` is defined I only check the one folder exists, but  I wanted to try and not leave any bugs in the stable code !  (Normally I leave it well alone).

Pushed changes a few minutes ago so you should be good to go!

**Comment by mike632t** [comment]
> What's your preference? 

Keep them both in `x11-calc-flathub` I think.

**Comment by mike632t** [comment]
> Build date may need to report which timezone date refers to, or always reports in UTC.

How `__DATE__` and `__TIME__` are handled depends entirely on the compiler - looking at the GCC manual thee doesn't seem to be any way to set or get the timezone used...

**Comment by macmpi** [comment]
> > Build date may need to report which timezone date refers to, or always reports in UTC.
> 
> How `__DATE__` and `__TIME__` are handled depends entirely on the compiler - looking at the GCC manual thee doesn't seem to be any way to set or get the timezone used...

Yes. Maybe replacing `__DATE__` and `__TIME__`  by sth like `$( TZ=UTC date '+%F %T %Z' )` would show same in all cases.

**Comment by mike632t** [comment]
> > > Build date may need to report which timezone date refers to, or always reports in UTC.
> > 
> > 
> > How `__DATE__` and `__TIME__` are handled depends entirely on the compiler - looking at the GCC manual thee doesn't seem to be any way to set or get the timezone used...
> 
> Yes. Maybe replacing `__DATE__` and `__TIME__` by sth like `$( TZ=UTC date '+%F %T %Z' )` would show same in all cases.

I really liked that idea but unfortunately it will only work only on Linux, and I don't really want to mess with `__TIME__` and `__DATE__` for compatibility reasons, if I want to know what the code base is I'd check the commit id over the date/time every time.  I'm really chuffed to have found a way to get that in the code when building from a git clone (mostly thanks to your very useful tip).

**Comment by macmpi** [comment]
Building from v0.11.0122 tag seems to work: yeah!
Looks-like we are getting ready for initial submission: will let it rest for the night.

**Comment by macmpi** [comment]
Added GUI setup as suggested: you may check this one.
[x11-calc.flatpak.tar.gz](https://github.com/macmpi/x11-calc-flatpak/files/14358170/x11-calc.flatpak.tar.gz)
Setup can also be initiated with right-click on icon (on desktops supporting .desktop actions).

Also added automated build: if all goes well after initial publication (not done yet), every time you will tag a new release, flathub would automagically update repofiles and build new version within an hour, and then publish the update an hour later...

**Comment by mike632t** [comment]
Love it.

Is there any chance you could make it launch the selected emulator automatically?   Having the launcher just die after selecting the model is a bit confusing and even better could it automatically prompt the user to select the default model if it is not configured (without having to use `--setup` to launch it the first time)?

Being able to trap any errors in the script and have `zenity` display a the error message on exit would be nice - that way if the user selects a voyager model they will see an error that says no firmware is loaded?  
```
zenity --error --text="x11-calc-10c : Empty ROM - no firmware loaded.'"
```

If I was being picky I'd describe the field as 'Model' rather then 'Models' in the first dialog, as the user is selecting the model they  want to use, and I'd expand the Model number to be 'HP 10c', 'HP 11c', 'HP 12c',...  (but I also know why you haven't done that, and I don't think it is worth the effort to change it).   I'd also label the buttons  'Cancel', and 'OK' as this is more normal (but to me RPN seems normal too...) 

Also personally I don't think the second dialog actually adds much, it is sort of an expert mode, and if you are that sort of user then just editing the config file should not be a big deal.   Having to make a second selection slows things down and unless the user has read the documentation they wont know what it is for anyway, and once they do understand they will have become an expert user already!

Sorry about the delay responding - been trying to figure out how to enable 2FA as it appears I will shortly need it to use GitHub, but there is no mobile signal here which makes things a bit difficult.

**Comment by mike632t** [comment]
> automagically update repofiles and build new version within an hour

Nice - but from here on in `stable` is really going to have to mean `stable`!!  

This does mean any testing of any sort will have to be against `unstable`, which was the kind of the idea anyway...

**Comment by mike632t** [comment]
Mind if I 'borrow' bits of your launcher script?

If I add a shell script `x11-calc-launcher.sh` and desktop file `x11-calc.desktop` to my `src` folder does that conflict with anything in your Flatpak build?

**Comment by macmpi** [comment]
> Love it.
> 
> Is there any chance...

Thanks for the detailed feedback: I'll try to add some bits before submitting (BTW, one can launch without --setup initially, and it will indeed use default calc).

>Mind if I 'borrow' bits of your launcher script?

>If I add a shell script x11-calc-launcher.sh and desktop file x11-calc.desktop to my src folder does that conflict with >anything in your Flatpak build?

Glad to see you buy-in the launcher idea actually :wink: : I was about to suggest launcher might probably need to land into the core app moving forward. Ideally flatpak stuff is just a packaging of the core app: had to do the launcher to have a single entrypoint/icon initially...
If you take it on your side, can you please use same XDG convention for any `.conf` file, to ease integration?

How shall we proceed: we do a first iteration mostly as-is (launcher in flatpak side), and you work-out the new launcher for next stable release? Or you feel you may take it over straightaway?
Great teamwork :+1:

**Comment by mike632t** [comment]
I think I'd prefer to leave the Flatpak launcher functionality separate for now (it works!).

I just want to make sure there isn't a clash with your package.   

What I had in mind for the moment was simply a launcher that allowed me to select which model to I wanted to use __every__ time the application was launched.  I liked it that much!  However, this might become annoying so I want to experiment and see what works and I defiantly don't want to impose any changes on your package.

Saving the options (like the ROM location etc) for each model in an `x11-calc.conf` or `x11-calc.xml` file is something I was going to think about later.   I can probably come up with a custom launcher using the GTK tooklit, but may opt for wxWidgets instead, even thought that means using C++ and ideally I'd want to wrap the existing application in a window with a menu etc...

Right now I have no idea how that might work, well perhaps I have a very small idea, but it isn't anything quick or easy and I'd like to get the HP10 emulation working first which means a lot of very tedious debugging...

**Comment by macmpi** [comment]
> I think I'd prefer to leave the Flatpak launcher functionality separate for now (it works!).
> 
> I just want to make sure there isn't a clash with your package.

OK. Implemented some of the suggestions, and will initiate flathub submission.

>This does mean any testing of any sort will have to be against unstable, which was the kind of the idea anyway...

Flatpak build automation is only triggered by a _higher version **tag**_: new commits without version tag will not trigger it.
I disabled bot auto-merge for now, as some upcoming update (like HP10 addition,...) may also require packaging changes (i.e. setup in launcher).
Let's keep in touch.

**Comment by mike632t** [comment]
Errors building - don't know if you have seen the notification

https://buildbot.flathub.org/#/builders/6/builds/101969

`The flathub.json file had publish-delay-hours with value less than 3`

**Comment by macmpi** [comment]
yes, fixed that one I think :wink:

**Comment by macmpi** [comment]
I see you are a Pi user (Pi3+ at least): do you have a 64-bit Raspberry Pi OS setup on which [flatpak could be installed](https://flathub.org/setup/Raspberry%20Pi%20OS) to try the `aarch64` release?

**Comment by macmpi** [comment]
[done](https://github.com/flathub/io.github.mike632t.x11-calc)
