### ISSUE TITLE
Default location for add-on roms

### ISSUE THREAD

**Issue by macmpi** [macmpi/x11-calc-flatpak#7]
@mike632t, now `. dat` files are in `~/.local/share/x11-calc`  (or XDG related), I'm quite inclined to assume _user-installed roms_ (for voyager models in particular) should land in same location, or eventually in a `roms` subdir from there.
Having some sort of default location helps users keeping things simple & tidy, although they may explicitly use other location with cmdline.
(BTW I've set `prg` directory as `/app/share/x11-calc/prg/`, as this one is _distributed with the app_)

I'm interested in your feedback on the followings:
- keep roms in `x11-calc` (like for `.dat` files), or in a `roms` subdirectory there (file names after `$model.rom`)?
- currently my launch script assumes that default location for voyager roms if no `-r` option with `.rom` extension is passed: would you be inclined into using that same default & check in your app side?
If so I'd remove that check on the launch script.

`

**Comment by mike632t** [comment]
Specifying a `.rom` file without a path using -r  will result in the program searching for the file in the current working directory, I'm not sure if it is allowed in Flatpak but if your script set the current working directory to the same directory as the binary (executable) files it would make sense to store the `.rom` files there (which is where i put them on my machine).  If it happens to be a folder the user doesn't have write access to then that probably isn't a bad thing. 

On my machine I've moved all my saved programs into the same folder as the other `.dat` files, as they are basically the same thing, and this keeps things simple.

If you want to display a graphical drop down list from a bash script take a look at `zenity`, it might be what you are looking for.

**Comment by macmpi** [comment]
As .rom files are not supplied with app, but are to be supplied by users, it has to be in the `XDG_DATA_HOME` area.
rm being provided with app, it is in app space in flatpak (flatpak does not seem to be able to install  files in `XDG_DATA_HOME` area).
So I'll keep locations as-is then, and keep the `.rom` default path logic in launch script.

Thanks for the tip on `zenity`: will check.

**Comment by mike632t** [comment]
You weren't tempted to download them from Eric SMITH's [nonpareil](https://github.com/brouhaha/nonpareil/) repository ?

For an example script using `zenity` look [here](https://mike632t.wordpress.com/2013/02/17/usb-console-script/), and yes - if I could make a bash script look more like PASCAL I would!!

**Comment by macmpi** [comment]
> You weren't tempted to download them from Eric SMITH's [nonpareil](https://github.com/brouhaha/nonpareil/) repository ?

Yes, that's where I got them for tests. Wondering why `x11-calc` would not import them initially: licensing issue?
Unsure what are the few changes over the 0.97 ones.

> For an example script using `zenity` look [here](https://mike632t.wordpress.com/2013/02/17/usb-console-script/), and yes - if I could make a bash script look more like PASCAL I would!!

:smile: Thanks.
